export const LOAD_RATES_REQUEST = 'LOAD_RATES_REQUEST'
export const LOAD_RATES_SUCCESS = 'LOAD_RATES_SUCCESS'
export const LOAD_RATES_FAILURE = 'LOAD_RATES_FAILURE'
export const ADD_RATE = 'ADD_RATE'
